name: NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Fix Windows Git autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npm run build
    - run: npm run test
